
REM START MAPINFO MAPINFO_MAPCATALOG

  DROP   TABLE "MAPINFO"."MAPINFO_MAPCATALOG" PURGE;

  CREATE TABLE "MAPINFO"."MAPINFO_MAPCATALOG" 
   (	"SPATIALTYPE" NUMBER, 
	"TABLENAME" VARCHAR2(32 BYTE), 
	"OWNERNAME" VARCHAR2(32 BYTE), 
	"SPATIALCOLUMN" VARCHAR2(32 BYTE), 
	"DB_X_LL" NUMBER, 
	"DB_Y_LL" NUMBER, 
	"DB_X_UR" NUMBER, 
	"DB_Y_UR" NUMBER, 
	"COORDINATESYSTEM" VARCHAR2(254 BYTE), 
	"SYMBOL" VARCHAR2(254 BYTE), 
	"XCOLUMNNAME" VARCHAR2(32 BYTE), 
	"YCOLUMNNAME" VARCHAR2(32 BYTE), 
	"RENDITIONTYPE" NUMBER(*,0), 
	"RENDITIONCOLUMN" VARCHAR2(32 BYTE), 
	"RENDITIONTABLE" VARCHAR2(32 BYTE)
   );
 
REM END MAPINFO MAPINFO_MAPCATALOG

REM START MAPINFO MAPINFO_MAPCATALOG_INDEX

CREATE UNIQUE INDEX "MAPINFO"."MAPINFO_MAPCATALOG_INDEX" ON "MAPINFO"."MAPINFO_MAPCATALOG" ("TABLENAME", "OWNERNAME") ;
 
REM END MAPINFO MAPINFO_MAPCATALOG_INDEX

QUIT;

