DROP TABLE COLUMN_ANALYSES;
DROP TABLE COLUMN_analysis_summaries;
DROP TABLE FEATURE_ERRORS;
DROP TABLE FEATURE_ERROR_SUMMARIES;
DROP TABLE MANAGED_COLUMNS;
DROP SEQUENCE MANAGED_COLUMNS_ID;
CREATE SEQUENCE MANAGED_COLUMNS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
GRANT SELECT ON MANAGED_COLUMNS_ID TO PUBLIC;
CREATE TABLE MANAGED_COLUMNS (
  ID                      INTEGER,
  owner                   VARCHAR2(32),
  table_name              VARCHAR2(32),
  column_name             VARCHAR2(32),
  min_vertices            NUMBER,
  avg_vertices            NUMBER,
  max_vertices            NUMBER,
  vertex_date             DATE
);
GRANT INSERT,UPDATE,DELETE,SELECT 
   ON MANAGED_COLUMNS 
   TO PUBLIC;
ALTER TABLE MANAGED_COLUMNS 
  ADD CONSTRAINT MANAGED_COLUMNS_PK
      PRIMARY KEY (ID);
ALTER TABLE MANAGED_COLUMNS 
  ADD CONSTRAINT MANAGED_COLUMNS_MUNQ
      UNIQUE (owner, table_name, column_name);
ALTER TABLE MANAGED_COLUMNS 
  ADD CONSTRAINT MANAGED_COLUMNS_FK
      FOREIGN KEY (owner, table_name, column_name) 
      REFERENCES ALL_SDO_GEOM_METADATA(owner, table_name, column_name) ;
-- Need ON CASCADE DELETE?

Prompt Table for reporting result of the running the Tool.MetadataAnalysis procedure
Prompt against a particular table.
DROP SEQUENCE COLUMN_ANALYSES_ID;
CREATE SEQUENCE COLUMN_ANALYSES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
GRANT SELECT ON COLUMN_ANALYSES_ID TO PUBLIC;
CREATE TABLE COLUMN_ANALYSES (
  ID                INTEGER,
  Managed_Column_ID INTEGER,
  analysis_date     TIMESTAMP,
  result            VARCHAR2(4000)
);
GRANT INSERT,UPDATE,DELETE,SELECT 
   ON COLUMN_ANALYSES 
   TO PUBLIC;
ALTER TABLE COLUMN_ANALYSES 
  ADD CONSTRAINT COLUMN_ANALYSES_PK
      PRIMARY KEY (ID);
ALTER TABLE COLUMN_ANALYSES 
  ADD CONSTRAINT COLUMN_ANALYSES_FK
      FOREIGN KEY (Managed_Column_ID)
      REFERENCES MANAGED_COLUMNS(ID) 
      ON DELETE CASCADE;

DROP SEQUENCE COLUMN_ANALYSIS_SUMMARIES_ID;
CREATE SEQUENCE COLUMN_ANALYSIS_SUMMARIES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
GRANT SELECT ON COLUMN_ANALYSIS_SUMMARIES_ID TO PUBLIC;
CREATE TABLE COLUMN_ANALYSIS_SUMMARIES (
  ID                      INTEGER,
  Managed_Column_ID       INTEGER,
  analysis_process_start  DATE,
  analysis_process_end    DATE
);
GRANT INSERT,UPDATE,DELETE,SELECT 
   ON COLUMN_analysis_summaries
   TO PUBLIC;
ALTER TABLE COLUMN_analysis_summaries
  ADD CONSTRAINT COLUMN_analysis_summaries_PK
      PRIMARY KEY (ID);
ALTER TABLE COLUMN_analysis_summaries
  ADD CONSTRAINT COLUMN_analysis_summaries_FK
      FOREIGN KEY (Managed_Column_ID)
      REFERENCES MANAGED_COLUMNS(ID) 
      ON DELETE CASCADE;

DROP SEQUENCE FEATURE_ERRORS_ID;
CREATE SEQUENCE FEATURE_ERRORS_ID START WITH 1 INCREMENT BY 1 NOCACHE;
GRANT SELECT ON FEATURE_ERRORS_ID TO PUBLIC;
CREATE TABLE FEATURE_ERRORS (
  ID                 INTEGER,
  Managed_Column_ID  INTEGER,
  feature_rowid      UROWID,
  error_code         VARCHAR2(10),
  error_status       CHAR(1),
  error_context      VARCHAR2(2000),
  error_date         DATE
);
GRANT INSERT,UPDATE,DELETE,SELECT 
   ON FEATURE_ERRORS 
   TO PUBLIC;
ALTER TABLE FEATURE_ERRORS
  ADD CONSTRAINT FEATURE_ERRORS_PK
      PRIMARY KEY (ID);
ALTER TABLE FEATURE_ERRORS 
  ADD CONSTRAINT FEATURE_ERRORS_FK
      FOREIGN KEY (Managed_Column_ID)
      REFERENCES MANAGED_COLUMNS(ID) 
      ON DELETE CASCADE;

DROP SEQUENCE FEATURE_ERRORS_SUMMARIES_ID;
CREATE SEQUENCE FEATURE_ERRORS_SUMMARIES_ID START WITH 1 INCREMENT BY 1 NOCACHE;
GRANT SELECT ON FEATURE_ERRORS_SUMMARIES_ID TO PUBLIC;
CREATE TABLE FEATURE_ERROR_SUMMARIES (
  ID                 INTEGER,
  Managed_Column_ID  INTEGER,
  predicate          VARCHAR2(4000),
  process_start      Date,
  process_end        Date,
  process_count      Integer,
  error_total        Integer,
  error_fixed        Integer
);
GRANT INSERT,UPDATE,DELETE,SELECT 
   ON FEATURE_ERROR_SUMMARIES 
   TO PUBLIC;
ALTER TABLE FEATURE_ERROR_SUMMARIES
  ADD CONSTRAINT FEATURE_ERROR_SUMAMRIES_PK
      PRIMARY KEY (ID);
ALTER TABLE FEATURE_ERROR_SUMMARIES 
  ADD CONSTRAINT FEATURE_ERROR_SUMMARIES_FK
      FOREIGN KEY (Managed_Column_Id)
      REFERENCES MANAGED_COLUMNS (ID)
      ON DELETE CASCADE;

QUIT;
