/* Generated By:JavaCC: Do not edit this line. PLSQLParserConstants.java */
/* Copyright (C) 2002 Albert Tumanov

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

*/

package net.sourceforge.pldoc.parser;

public interface PLSQLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 32;
  int FORMAL_COMMENT = 33;
  int MULTI_LINE_COMMENT = 34;
  int REPLACE = 36;
  int DEFINER = 37;
  int CURRENT_USER = 38;
  int SERIALLY_REUSABLE = 39;
  int RESTRICT_REFERENCES = 40;
  int EXCEPTION_INIT = 41;
  int AUTONOMOUS_TRANSACTION = 42;
  int LANGUAGE = 43;
  int ALL = 44;
  int ALTER = 45;
  int AND = 46;
  int ANY = 47;
  int ARRAY = 48;
  int AS = 49;
  int ASC = 50;
  int AT = 51;
  int AUTHID = 52;
  int AVG = 53;
  int BEGIN = 54;
  int BETWEEN = 55;
  int BINARY_INTEGER = 56;
  int BODY = 57;
  int BOOLEAN = 58;
  int BULK = 59;
  int BY = 60;
  int CASE = 61;
  int CHAR = 62;
  int CHAR_BASE = 63;
  int CHECK = 64;
  int CLOSE = 65;
  int CLUSTER = 66;
  int COALESCE = 67;
  int COLLECT = 68;
  int COLUMN = 69;
  int COMMENT = 70;
  int COMMIT = 71;
  int COMPRESS = 72;
  int CONNECT = 73;
  int CONSTANT = 74;
  int CREATE = 75;
  int CURRENT = 76;
  int CURRVAL = 77;
  int CURSOR = 78;
  int DATE = 79;
  int DAY = 80;
  int DECLARE = 81;
  int DECIMAL = 82;
  int _DEFAULT = 83;
  int DELETE = 84;
  int DESC = 85;
  int DETERMINISTIC = 86;
  int DISTINCT = 87;
  int DO = 88;
  int DROP = 89;
  int ELSE = 90;
  int ELSIF = 91;
  int END = 92;
  int EXCEPTION = 93;
  int EXCLUSIVE = 94;
  int EXECUTE = 95;
  int EXISTS = 96;
  int EXIT = 97;
  int EXTENDS = 98;
  int EXTRACT = 99;
  int FALSE = 100;
  int FETCH = 101;
  int FLOAT = 102;
  int FOR = 103;
  int FORALL = 104;
  int FROM = 105;
  int FUNCTION = 106;
  int GOTO = 107;
  int GROUP = 108;
  int HAVING = 109;
  int HEAP = 110;
  int HOUR = 111;
  int IF = 112;
  int IMMEDIATE = 113;
  int IN = 114;
  int INDEX = 115;
  int INDEXTYPE = 116;
  int INDICATOR = 117;
  int INSERT = 118;
  int INTEGER = 119;
  int INTERFACE = 120;
  int INTERSECT = 121;
  int INTERVAL = 122;
  int INTO = 123;
  int IS = 124;
  int ISOLATION = 125;
  int JAVA = 126;
  int LEVEL = 127;
  int LIKE = 128;
  int LIMIT = 129;
  int LIMITED = 130;
  int LOCK = 131;
  int LONG = 132;
  int LOOP = 133;
  int MAX = 134;
  int MERGE = 135;
  int MIN = 136;
  int MINUS = 137;
  int MINUTE = 138;
  int MLSLABEL = 139;
  int MOD = 140;
  int MODE = 141;
  int MONTH = 142;
  int NATURAL = 143;
  int NATURALN = 144;
  int NEW = 145;
  int NEXTVAL = 146;
  int NOCOPY = 147;
  int NOT = 148;
  int NOWAIT = 149;
  int NULL = 150;
  int NULLIF = 151;
  int NUMBER = 152;
  int NUMBER_BASE = 153;
  int OCIROWID = 154;
  int OF = 155;
  int ON = 156;
  int OPAQUE = 157;
  int OPEN = 158;
  int OPERATOR = 159;
  int OPTION = 160;
  int OR = 161;
  int ORDER = 162;
  int ORGANIZATION = 163;
  int OTHERS = 164;
  int OUT = 165;
  int PACKAGE = 166;
  int PARALLEL_ENABLE = 167;
  int PARTITION = 168;
  int PCTFREE = 169;
  int PIPELINED = 170;
  int PLS_INTEGER = 171;
  int POSITIVE = 172;
  int POSITIVEN = 173;
  int PRAGMA = 174;
  int PRIOR = 175;
  int PRIVATE = 176;
  int PROCEDURE = 177;
  int PUBLIC = 178;
  int RAISE = 179;
  int RANGE = 180;
  int RAW = 181;
  int REAL = 182;
  int RECORD = 183;
  int REF = 184;
  int RELEASE = 185;
  int RETURN = 186;
  int REVERSE = 187;
  int ROLLBACK = 188;
  int ROW = 189;
  int ROWID = 190;
  int ROWNUM = 191;
  int ROWTYPE = 192;
  int SAVEPOINT = 193;
  int SECOND = 194;
  int SELECT = 195;
  int SEPARATE = 196;
  int SET = 197;
  int SHARE = 198;
  int SMALLINT = 199;
  int SPACE = 200;
  int SQL = 201;
  int SQLCODE = 202;
  int SQLERRM = 203;
  int START = 204;
  int STDDEV = 205;
  int SUBTYPE = 206;
  int SUCCESSFUL = 207;
  int SUM = 208;
  int SYNONYM = 209;
  int SYSDATE = 210;
  int TABLE = 211;
  int THEN = 212;
  int TIME = 213;
  int TIMESTAMP = 214;
  int TIMEZONE_REGION = 215;
  int TIMEZONE_ABBR = 216;
  int TIMEZONE_MINUTE = 217;
  int TIMEZONE_HOUR = 218;
  int TO = 219;
  int TRANSACTION = 220;
  int TRIGGER = 221;
  int TRUE = 222;
  int TYPE = 223;
  int UI = 224;
  int USING = 225;
  int WHEN = 226;
  int WHILE = 227;
  int UPDATE = 228;
  int VARCHAR = 229;
  int VARCHAR2 = 230;
  int DOUBLE = 231;
  int DEC = 232;
  int PRECISION = 233;
  int INT = 234;
  int NUMERIC = 235;
  int SIGNTYPE = 236;
  int NCHAR = 237;
  int NVARCHAR2 = 238;
  int STRING = 239;
  int UROWID = 240;
  int VARRAY = 241;
  int VARYING = 242;
  int BFILE = 243;
  int BLOB = 244;
  int CLOB = 245;
  int NCLOB = 246;
  int YEAR = 247;
  int LOCAL = 248;
  int WITH = 249;
  int ZONE = 250;
  int CHARACTER = 251;
  int AFTER = 252;
  int BEFORE = 253;
  int INSTEADOF = 254;
  int FOREACHROW = 255;
  int REFERENCING = 256;
  int OLD = 257;
  int PARENT = 258;
  int VIEW = 259;
  int UNION = 260;
  int GERMAN_SPECIAL_CHARACTERS = 261;
  int LETTER = 262;
  int DIGIT = 263;
  int _CHARACTER = 264;
  int _CHARACTER_WO_ASTERISK = 265;
  int SPECIAL_CHARACTERS = 266;
  int DELIMITER = 267;
  int IDENTIFIER = 268;
  int UNSIGNED_NUMERIC_LITERAL = 269;
  int FLOAT_LITERAL = 270;
  int INTEGER_LITERAL = 271;
  int _WHATEVER_CHARACTER_WO_ASTERISK = 272;
  int CHARACTER_LITERAL = 273;
  int STRING_LITERAL = 274;

  int DEFAULT = 0;
  int IN_FORMAL_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;
  int IN_SQL_STATEMENT_ENDED_SEMICOLON = 3;

  String[] tokenImage = {
    "<EOF>",
    "\"/\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".attach\"",
    "\",\"",
    "\":=\"",
    "\"%\"",
    "\"..\"",
    "\"<<\"",
    "\">>\"",
    "\"=\"",
    "\"!=\"",
    "\"<>\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"*\"",
    "\"=>\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 30>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 35>",
    "\"REPLACE\"",
    "\"DEFINER\"",
    "\"CURRENT_USER\"",
    "\"SERIALLY_REUSABLE\"",
    "\"RESTRICT_REFERENCES\"",
    "\"EXCEPTION_INIT\"",
    "\"AUTONOMOUS_TRANSACTION\"",
    "\"LANGUAGE\"",
    "\"ALL\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AT\"",
    "\"AUTHID\"",
    "\"AVG\"",
    "\"BEGIN\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BODY\"",
    "\"BOOLEAN\"",
    "\"BULK\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CHAR\"",
    "\"CHAR_BASE\"",
    "\"CHECK\"",
    "\"CLOSE\"",
    "\"CLUSTER\"",
    "\"COALESCE\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"COMPRESS\"",
    "\"CONNECT\"",
    "\"CONSTANT\"",
    "\"CREATE\"",
    "\"CURRENT\"",
    "\"CURRVAL\"",
    "\"CURSOR\"",
    "\"DATE\"",
    "\"DAY\"",
    "\"DECLARE\"",
    "\"DECIMAL\"",
    "\"DEFAULT\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DETERMINISTIC\"",
    "\"DISTINCT\"",
    "\"DO\"",
    "\"DROP\"",
    "\"ELSE\"",
    "\"ELSIF\"",
    "\"END\"",
    "\"EXCEPTION\"",
    "\"EXCLUSIVE\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"EXTENDS\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FORALL\"",
    "\"FROM\"",
    "\"FUNCTION\"",
    "\"GOTO\"",
    "\"GROUP\"",
    "\"HAVING\"",
    "\"HEAP\"",
    "\"HOUR\"",
    "\"IF\"",
    "\"IMMEDIATE\"",
    "\"IN\"",
    "\"INDEX\"",
    "\"INDEXTYPE\"",
    "\"INDICATOR\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERFACE\"",
    "\"INTERSECT\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"LEVEL\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LIMITED\"",
    "\"LOCK\"",
    "\"LONG\"",
    "\"LOOP\"",
    "\"MAX\"",
    "\"MERGE\"",
    "\"MIN\"",
    "\"MINUS\"",
    "\"MINUTE\"",
    "\"MLSLABEL\"",
    "\"MOD\"",
    "\"MODE\"",
    "\"MONTH\"",
    "\"NATURAL\"",
    "\"NATURALN\"",
    "\"NEW\"",
    "\"NEXTVAL\"",
    "\"NOCOPY\"",
    "\"NOT\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NULLIF\"",
    "\"NUMBER\"",
    "\"NUMBER_BASE\"",
    "\"OCIROWID\"",
    "\"OF\"",
    "\"ON\"",
    "\"OPAQUE\"",
    "\"OPEN\"",
    "\"OPERATOR\"",
    "\"OPTION\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORGANIZATION\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"PACKAGE\"",
    "\"PARALLEL_ENABLE\"",
    "\"PARTITION\"",
    "\"PCTFREE\"",
    "\"PIPELINED\"",
    "\"PLS_INTEGER\"",
    "\"POSITIVE\"",
    "\"POSITIVEN\"",
    "\"PRAGMA\"",
    "\"PRIOR\"",
    "\"PRIVATE\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"RAISE\"",
    "\"RANGE\"",
    "\"RAW\"",
    "\"REAL\"",
    "\"RECORD\"",
    "\"REF\"",
    "\"RELEASE\"",
    "\"RETURN\"",
    "\"REVERSE\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"ROWID\"",
    "\"ROWNUM\"",
    "\"ROWTYPE\"",
    "\"SAVEPOINT\"",
    "\"SECOND\"",
    "\"SELECT\"",
    "\"SEPARATE\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"SPACE\"",
    "\"SQL\"",
    "\"SQLCODE\"",
    "\"SQLERRM\"",
    "\"START\"",
    "\"STDDEV\"",
    "\"SUBTYPE\"",
    "\"SUCCESSFUL\"",
    "\"SUM\"",
    "\"SYNONYM\"",
    "\"SYSDATE\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMEZONE_REGION\"",
    "\"TIMEZONE_ABBR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TIMEZONE_HOUR\"",
    "\"TO\"",
    "\"TRANSACTION\"",
    "\"TRIGGER\"",
    "\"TRUE\"",
    "\"TYPE\"",
    "\"UI\"",
    "\"USING\"",
    "\"WHEN\"",
    "\"WHILE\"",
    "\"UPDATE\"",
    "\"VARCHAR\"",
    "\"VARCHAR2\"",
    "\"DOUBLE\"",
    "\"DEC\"",
    "\"PRECISION\"",
    "\"INT\"",
    "\"NUMERIC\"",
    "\"SIGNTYPE\"",
    "\"NCHAR\"",
    "\"NVARCHAR2\"",
    "\"STRING\"",
    "\"UROWID\"",
    "\"VARRAY\"",
    "\"VARYING\"",
    "\"BFILE\"",
    "\"BLOB\"",
    "\"CLOB\"",
    "\"NCLOB\"",
    "\"YEAR\"",
    "\"LOCAL\"",
    "\"WITH\"",
    "\"ZONE\"",
    "\"CHARACTER\"",
    "\"AFTER\"",
    "\"BEFORE\"",
    "\"INSTEAD OF\"",
    "\"FOR EACH ROW\"",
    "\"REFERENCING\"",
    "\"OLD\"",
    "\"PARENT\"",
    "\"VIEW\"",
    "\"UNION\"",
    "<GERMAN_SPECIAL_CHARACTERS>",
    "<LETTER>",
    "<DIGIT>",
    "<_CHARACTER>",
    "<_CHARACTER_WO_ASTERISK>",
    "<SPECIAL_CHARACTERS>",
    "<DELIMITER>",
    "<IDENTIFIER>",
    "<UNSIGNED_NUMERIC_LITERAL>",
    "<FLOAT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<_WHATEVER_CHARACTER_WO_ASTERISK>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
  };

}
