DEFINE INSTALL_SCHEMA='&1'
set serveroutput on size unlimited
begin
  for REC in (select 'DROP TYPE ' || USER || '.' || OBJECT_NAME ||' FORCE' as sqlcmd
                from USER_OBJECTS 
                where OBJECT_NAME like 'ST_%' 
                 and OBJECT_TYPE = 'TYPE') LOOP
      execute immediate REC.SQLCMD;
      dbms_output.put_line('SUCCESSFUL: ' || rec.sqlcmd);
  end LOOP;
end;
/
show errors

DROP PACKAGE &&INSTALL_SCHEMA..DEBUG;
DROP PACKAGE &&INSTALL_SCHEMA..COGO;
DROP PACKAGE &&INSTALL_SCHEMA..TOOLS;
DROP PACKAGE &&INSTALL_SCHEMA..ST_LRS;
DROP TYPE &&INSTALL_SCHEMA..T_Geometries   FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Geometry     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_GeomObj      FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_GeomRow      FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Geometry_Row FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_ElemInfoSet  FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_ElemInfo     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Vectors      FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Segments     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_VectorObj    FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_SegmentObj   FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Vertices     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Grids        FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Grid         FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Vector       FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Segment      FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Vertex       FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_IntValues    FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_IntValue     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Tokens       FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Token        FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Vector3D     FORCE;
DROP TYPE &&INSTALL_SCHEMA..TBL_BEARING_DISTANCES FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_BEARING_DISTANCES   FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_BEARING_DISTANCE    FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Elem_Info_Array     FORCE;
DROP TYPE &&INSTALL_SCHEMA..T_Ordinate_Array      FORCE;

DROP TYPE &&INSTALL_SCHEMA..Vector3D      FORCE; -- Deprecated
DROP FUNCTION &&INSTALL_SCHEMA..Generate_Series; -- Deprecated
DROP FUNCTION &&INSTALL_SCHEMA..Tokenizer;       -- Deprecated

purge recyclebin;

exit;
