CREATE OR REPLACE PACKAGE test_t_segment 
AUTHID DEFINER
IS

   /* generated by utPLSQL for SQL Developer on 2019-07-26 12:11:59 
   *
   * NOTE:
   *   A lot of tests are self-referential. 
   *   Work must be done to compare to existing Oracle functions where a match exists.
   */

   --%suite(test_t_segment)
   --%suitepath(alltests)
   
   --%test circularArc Constructors for invalid Z ordinates
   PROCEDURE ST_CheckZ;
   --%test
   PROCEDURE ST_mbr;
   --%test
   PROCEDURE ST_minx;
   --%test
   PROCEDURE ST_maxx;
   --%test
   PROCEDURE ST_miny;
   --%test
   PROCEDURE ST_maxy;
   --%test
   PROCEDURE ST_ishorizontal;
   --%test
   PROCEDURE ST_isvertical;
   --%test
   PROCEDURE ST_midpoint;
   --%test
   PROCEDURE ST_setcoordinates;
   --%test
   PROCEDURE ST_angle;
   --%test
   PROCEDURE ST_bearing;
   --%test
   PROCEDURE ST_length;
   --%test
   PROCEDURE ST_distance;
   --%test
   PROCEDURE ST_AsEWKT;
   --%test
   PROCEDURE ST_Equals;
   --%test 
   PROCEDURE ST_FindCircle;
   --%test
   PROCEDURE ST_Densify;
   --%test
   PROCEDURE ST_segment_to_segment_distance;
   --%test
   PROCEDURE ST_offsetpoint;
   --%test
   PROCEDURE ST_offsetbetween;
   --%test(T_SEGMENT.ST_PointAlong)
   PROCEDURE ST_pointalong;
   --%test
   PROCEDURE ST_pointalongoffset;
   --%test
   PROCEDURE ST_computetangentpoint;
   --%test
   PROCEDURE ST_computetangentline;
   --%test
   PROCEDURE ST_linesubstring;
   --%test
   PROCEDURE ST_ComputeDeflectionAngle;
   --%test 
   PROCEDURE ST_Reverse;
   --%test 
   PROCEDURE ST_isReversed;
   --%test 
   PROCEDURE ST_Merge;
   --%test 
   PROCEDURE ST_isCollinear;
   --%test 
   PROCEDURE ST_isCircularArc;
   --%test 
   PROCEDURE ST_To2D;
   --%test 
   PROCEDURE ST_To3D;
   --%test 
   PROCEDURE ST_HasM;
   --%test 
   PROCEDURE ST_HasZ;
   --%test 
   PROCEDURE ST_Srid;
   --%test 
   PROCEDURE ST_Self;
   --%test
   PROCEDURE ST_Round;
   --%test
   PROCEDURE ST_LRS_Dim;
   --%test
   PROCEDURE ST_LRS_Measure_Length;
   --%test
   PROCEDURE ST_LRS_Compute_Measure;
   --%test
   PROCEDURE ST_LRS_Add_Measure;
   --%test
   PROCEDURE ST_PointToLinestring;
   --%test
   PROCEDURE ST_PointToCircularArc;
   --%test
   PROCEDURE ST_Closest;
   --%test
   PROCEDURE ST_isPointOnSegment;
   --%test
   PROCEDURE ST_ProjectPoint;
   --%test (T_SEGMENT.ST_IntersectCircularArc)
   PROCEDURE ST_IntersectCircularArc;
   --%test (T_SEGMENT.ST_Intersect2CircularArcs)
   PROCEDURE ST_Intersect2CircularArcs;

END test_t_segment;
/
show errors

create or replace PACKAGE BODY test_t_segment IS

   /* generated by utPLSQL for SQL Developer on 2019-07-26 12:11:59 */

   -- test CircularArcs for invalid Z ordinates
   PROCEDURE ST_CheckZ
   IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      invalidCirculararc EXCEPTION;
      PRAGMA EXCEPTION_INIT(invalidCircularArc,-20214);
      v_segment  T_segment;
   Begin
     --
     -- ST_CheckZ
     -- 
     l_actual   := T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,2.0, 252230.478,5527000.0,3.0)))
                     .ST_CheckZ();
     l_expected := 1;
     ut.expect(l_actual).to_equal(l_expected);

     -- Check CircularArc Constructor
     BEGIN
       l_actual   := 1;
       v_segment  := T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,1.0, 252230.478,5527000.0,1.0)));
       l_expected := 1;
       ut.expect(l_actual).to_equal(l_expected);

       -- Now an invalid one.
       l_expected := 0;
       v_segment  := T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,2.0, 252230.478,5527000.0,1.0)));
       l_expected := 1;
       EXCEPTION
         WHEN invalidCircularArc THEN 
           ut.expect(SQLERRM).to_equal('ORA-20214: Circular arc segments with Z values must have equal Z value for all 3 points.');
    End;
   end ST_CheckZ;

   --
   -- test ST_mbr case 1: ...
   --
   PROCEDURE ST_mbr 
   IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      v_segment  spdba.t_segment;
      v_mbr      varchar2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_mbr;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      v_mbr     := v_segment.ST_MBR().get_wkt();
      -- populate expected
      -- ...
      l_actual := case when v_mbr = 'POLYGON ((0.0 0.0, 1.0 0.0, 1.0 1.0, 0.0 1.0, 0.0 0.0))' then 1 else 0 end;
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_mbr;

   --
   -- test ST_minx case 1: ...
   --
   PROCEDURE ST_minx 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 0.0;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_minx;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
      l_actual  := v_segment.ST_MinX();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_minx;

   --
   -- test ST_maxx case 1: ...
   --
   PROCEDURE ST_maxx 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 1.0;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_maxx;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
      l_actual  := v_segment.ST_MaxX();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_maxx;

   --
   -- test ST_miny case 1: ...
   --
   PROCEDURE ST_miny 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 0.0;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_miny;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
      l_actual  := v_segment.ST_MinY();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_miny;

   --
   -- test ST_maxy case 1: ...
   --
   PROCEDURE ST_maxy 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 1.0;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_maxy;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
      l_actual  := v_segment.ST_MaxY();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_maxy;

   --
   -- test ST_ishorizontal case 1: ...
   --
   PROCEDURE ST_ishorizontal 
   IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_ishorizontal;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,0)));

      -- Case 1
      -- ...
      l_actual := v_segment.ST_isHorizontal();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 2
      l_expected := 0;
      l_actual   := v_segment.ST_isVertical();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

   END ST_ishorizontal;

   --
   -- test ST_isvertical case 1: ...
   --
   PROCEDURE ST_isvertical 
   IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_isvertical;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,0,1)));

      -- Case 1
      l_expected := 1;
      l_actual   := v_segment.ST_isVertical();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 2
      l_expected := 0;
      l_actual   := v_segment.ST_isHorizontal();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

   END ST_isvertical;

   --
   -- test ST_midpoint case 1: ...
   --
   PROCEDURE ST_midpoint 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000) := 'POINT (0.5 0.5)';
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_midpoint;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
     l_actual := v_segment.ST_MidPoint().ST_SdoGeometry().get_wkt();
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_midpoint;

   --
   -- test ST_setcoordinates case 1: ...
   --
   PROCEDURE ST_setCoordinates 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000) := 'LINESTRING (1.0 1.0, 3.0 3.0)';
      v_segment  spdba.t_segment;
   BEGIN
      -- populate actual
      -- t_segment.st_setcoordinates;
      v_segment := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,1)));
      -- populate expected
      -- ...
      v_segment.ST_SetCoordinates(
                   p_startCoord => SPDBA.T_VERTEX(p_x =>1,p_y=>1),
                   p_endCoord   => SPDBA.T_VERTEX(p_x =>3,p_y=>3)
                );
      l_actual := v_segment.ST_SdoGeometry().get_wkt();

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_setcoordinates;

   --
   -- test ST_angle case 1: ...
   --
   PROCEDURE ST_angle 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 0.785;
   BEGIN
      -- populate actual
      -- t_segment.st_angle;
      l_actual := round(T_Segment(sdo_geometry('LINESTRING(0 0,10 10)',null)).ST_Angle(),3);
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_angle;

   --
   -- test ST_bearing case 1: ...
   --
   PROCEDURE ST_bearing 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 45;
   BEGIN
      -- populate actual
      -- t_segment.st_bearing;
      -- Case 1: Planar
      l_actual := round(T_Segment(sdo_geometry('LINESTRING(0 0,10 10)',null)).ST_Bearing(p_normalize=>1),3);
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 2: Geodetic
      l_actual  := round(T_Segment(sdo_geometry('LINESTRING(147 -43,148 -43)',4326)).ST_Bearing(p_normalize=>1),3);
      l_expected := 90.341;
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_bearing;

   --
   -- test ST_length case 1: ...
   --
   PROCEDURE ST_length 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 45;
   BEGIN
      -- populate actual
      -- t_segment.st_length;
      -- Case 1: Planar LineString no unit
      l_actual := round(T_Segment(sdo_geometry('LINESTRING(5200000 300000,5200010 300010)',null)).ST_Length(p_unit=>NULL),3);
      l_expected := 14.142;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 2: Planar LineString + Unit
      l_actual := round(T_Segment(sdo_geometry('LINESTRING(5200000 300000,5200010 300010)',28355)).ST_Length(p_unit=>'unit=KM'),6);
      l_expected := 0.014142;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 3: Geodetic with m unit
      l_actual   := round(T_Segment(sdo_geometry('LINESTRING(147 -43,148 -43)',4327)).ST_Length(p_unit=>'unit=M'),3);
      l_expected := 81540.486;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 4: Geodetic KM unit
      l_actual   := round(T_Segment(sdo_geometry('LINESTRING(147 -43,148 -43)',4327)).ST_Length(p_unit=>'unit=KM'),3);
      l_expected := 81.54;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 5: Geodetic 3D M unit
      l_actual   := round(T_Segment(sdo_geometry(3002,8307,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147,-43,100.0,148,-43,210.1))).ST_Length(p_unit=>'unit=M'),3);
      l_expected := 81540.486;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 6: Circular Arc line string
      l_actual   := round(T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                         .ST_Length(p_unit=>'unit=M'),3);
      l_expected := 506.889;
      ut.expect(l_actual).to_equal(l_expected); 
      -- Case 7: Planar with Z
      l_actual := round(T_Segment(sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,2.0)))
                          .ST_Length(p_unit=>'unit=KM'),3);
      l_expected := 0.014;
      ut.expect(l_actual).to_equal(l_expected);
      -- Case 2D + Z + M LineString
      l_actual := Round(
                    T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_Length(p_unit=>'unit=M')
                      ,3);
      l_expected := 38.252;
      ut.expect(l_actual).to_equal(l_expected);

   END ST_length;

   -- Test ST_Distance case 1: ...
   --
   PROCEDURE ST_Distance 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 1;
      v_segment spdba.t_segment;
      v_vertex  spdba.t_vertex;
      v_centre  spdba.t_vertex;
   BEGIN
      -- populate actual
      -- t_segment.st_distance;

      -- Case 1: Planar 2D LineString no unit
      l_actual := T_Segment(
                    p_line       => sdo_geometry('LINESTRING(5200000 300000,5200010 300010)',28355),
                    p_segment_id => 1,
                    p_precision  => 3,
                    p_tolerance  => 0.005)
                   .ST_Distance(p_geometry=>sdo_geometry('POINT(5200100 300500)',28355),
                      p_unit      =>NULL
                  );
      l_expected := 498.197;
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 1: Planar 3D LineString no unit
      l_actual := T_Segment(sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,2.0)))
                   .ST_Distance(p_geometry=>sdo_geometry(3001,28355,sdo_point_type(5200100,300500,100.5),NULL,NULL),
                      p_unit      =>NULL
                  );
      l_expected := 507.841;
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 3: Geodetic 
      l_actual   := T_Segment(sdo_geometry('LINESTRING(147 -43,148 -43)',4326))
                      .ST_Distance(p_geometry=>sdo_geometry('POINT(147.5 -43.75)',4326),
                                   p_unit      =>'unit=M'
                    );
      l_expected := 83275.288;
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 5: Circular Arc line string
      v_segment := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)));
      v_centre  := v_segment.ST_FindCircle();
      v_vertex  := spdba.t_vertex(p_x=>v_centre.x,p_y=>v_centre.y,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>v_segment.ST_SRID());
      l_actual  := v_segment.ST_Distance(p_vertex    =>v_vertex,
                                         p_unit      =>'unit=M');
      l_expected := 94.111;
      ut.expect(l_actual).to_equal(l_expected); 
   END ST_Distance;

   -- 
   -- test st_densify
   -- 
   PROCEDURE ST_Densify 
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      l_actual := T_Geometry(
                    T_Segment(sdo_geometry('LINESTRING(0 0,10 10)',null))
                      .ST_Densify(
                          p_distance  => 1.4142135623731,
                          p_unit      => null 
                    ),0.005,2,1)
                    .ST_Round(3)
                    .ST_AsEWKT('TM9');
      l_expected := 'LINESTRING (0 0,1 1,2 2,3 3,4 4,5 5,6 6,7 7,8 8,9 9,10 10)';
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_Densify;

   --
   -- test ST_segment_to_segment_distance case 1: ...
   --
   PROCEDURE ST_segment_to_segment_distance 
   IS
      l_actual   NUMBER := 0;
      l_expected NUMBER := 1;
   BEGIN
      -- populate actual
      -- t_segment.st_segment_to_segment_distance;

      -- dbms_output.put_line('  Case 1: Segments Intersect');
      -- ...
      l_actual := round(
                     T_Segment(
                       sdo_geometry('LINESTRING(0 0,10 10)',null)
                     ).ST_SegmentToSegmentDistance(
                       t_segment(
                         sdo_geometry('LINESTRING(0 10,10 0)',null)
                        )
                     ),3);
      l_expected := 0.0;
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

      -- dbms_output.put_line('  case 2: Segments are Parallel');
      l_actual := T_Segment(
                    sdo_geometry('LINESTRING(0 0,10 10)',null)
                  ).ST_SegmentToSegmentDistance(
                       t_segment(
                         sdo_geometry('LINESTRING(0 1,10 11)',null)
                       )
                  );
      l_expected := -9;
      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END ST_segment_to_segment_distance;

   --
   -- test ST_offsetpoint case 1: ...
   --
   PROCEDURE ST_OffsetPoint 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_offsetpoint;
RETURN;
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>-5,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>152.19245167,p_y=>-44.85985059,p_z=>7575,p_w=>NULL,p_id=>0,p_sdo_gtype=>3301,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>0,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>147.4775,p_y=>-43.19575,p_z=>7575,p_w=>NULL,p_id=>0,p_sdo_gtype=>3301,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>5,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>142.76254833,p_y=>-41.53164941,p_z=>7575,p_w=>NULL,p_id=>0,p_sdo_gtype=>3301,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>-5,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>152.19245167,p_y=>-44.85985059,p_z=>NULL,p_w=>NULL,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>0,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>147.4775,p_y=>-43.19575,p_z=>NULL,p_w=>NULL,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_OffsetPoint(p_ratio=>0.25,p_offset=>5,p_unit=>'unit=M').ST_Round(8).ST_AsText();
      l_expected := 'T_Vertex(p_x=>142.76254833,p_y=>-41.53164941,p_z=>NULL,p_w=>NULL,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4326)';
      ut.expect(l_actual).to_equal(l_expected);

      -- *******************
      -- Circular Arcs...
      l_actual   := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                     .ST_OffsetPoint(p_ratio=>0.25,p_offset=>5,p_unit=>'unit=M')
                     .ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (252335.098 5526872.307)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                      .ST_OffsetPoint(p_ratio=>0.25,p_offset=>0,p_unit=>'unit=M')
                      .ST_Round(3)
                      .ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (252336.21 5526867.432)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                      .ST_OffsetPoint(p_ratio=>0.25,p_offset=>-5,p_unit=>'unit=M')
                      .ST_Round(3)
                      .ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (252337.322 5526862.557)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,1.0, 252230.478,5527000.0,1.0)))
                      .ST_OffsetPoint(p_ratio=>0.25,p_offset=>5,p_unit=>'unit=M')
                      .ST_Round(3)
                      .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (252335.098 5526872.307 1)';
      ut.expect(l_actual).to_equal(l_expected);
   END ST_offsetpoint;

   --
   -- test ST_OffsetBetween case 1: ...
   --itunes
   PROCEDURE ST_OffsetBetween 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_offsetbetween;
      l_actual := T_Segment(SDO_GEOMETRY(2002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171, 562044.981,1013076.691)))
                    .ST_OffsetBetween(
                        p_segment      => T_Segment(SDO_GEOMETRY(2002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(562044.981,1013076.691, 562024.253,1013138.371))),
                        p_offset       => -5.0,
                        p_unit         => 'unit=M'
                    )
                    .ST_Round(3)
                    .ST_AsText();
      l_expected := 'T_Vertex(p_x=>562041.963,p_y=>1013080.677,p_z=>NULL,p_w=>NULL,p_id=>2,p_sdo_gtype=>2001,p_sdo_srid=>90000006)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
                    p_line       => SDO_GEOMETRY(3302,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00, 562044.981,1013076.691,77.1)),
                    p_segment_id => 1,
                    p_precision  => 3,
                    p_tolerance  => 0.005
                  ).ST_OffsetBetween(
                        p_segment      => T_Segment(SDO_GEOMETRY(3302,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(562044.981,1013076.691,77.1, 562024.253,1013138.371,142.2))),
                        p_offset       => -5.0,
                        p_unit         => 'unit=M'
                    )
                    .ST_Round(3)
                    .ST_AsText();
     l_expected := 'T_Vertex(p_x=>562041.963,p_y=>1013080.677,p_z=>77.1,p_w=>NULL,p_id=>2,p_sdo_gtype=>3301,p_sdo_srid=>90000006)';
     ut.expect(l_actual).to_equal(l_expected);

     -- Geodetic 3D
     l_actual := T_Segment(
                   p_line       => SDO_GEOMETRY(3302,8307,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(147.7868589596,-45.0326616056,0.0, 147.7876729555,-45.0330473956,77.1)),
                   p_segment_id => 1,
                   p_precision  => 8,
                   p_tolerance  => 0.005
                 ).ST_OffsetBetween(
                      p_segment => T_Segment(SDO_GEOMETRY(3302,8307,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(147.7876729555,-45.0330473956,77.1, 147.787402221,-45.032494027,142.2))),
                      p_offset  => -5.0,
                      p_unit    => 'unit=M'
                 ).ST_Round(8)
                  .ST_AsEWKT();
      l_expected := 'SRID=8307;POINTM (147.78762781 -45.03301578 77.1)'; 
      ut.expect(l_actual).to_equal(l_expected);  

      -- Geodetic 2D
      l_actual := T_Segment(
                    p_line       => SDO_GEOMETRY(2002,4326,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(147.7868589596,-45.0326616056, 147.7876729555,-45.0330473956)),
                    p_segment_id => 1,
                    p_precision  => 8,
                    p_tolerance  => 0.005
                 ).ST_OffsetBetween(
                        p_segment      => T_Segment(SDO_GEOMETRY(2002,4326,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(147.7876729555,-45.0330473956, 147.787402221,-45.032494027))),
                        p_offset       => 5.0,
                        p_unit         => 'unit=M'
                    )
                    .ST_Round(8)
                    .ST_AsEWKT();
      l_expected := 'SRID=4326;POINT (147.7877181 -45.03307901)';
      ut.expect(l_actual).to_equal(l_expected);  

      -- SGG: Need CircularArcTests
   END ST_offsetbetween;

   --
   -- test ST_pointalong case 1: ...
   --
   PROCEDURE ST_PointAlong 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_pointalong;
      l_actual := T_Segment(SDO_GEOMETRY(2002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171, 562044.981,1013076.691)))
                    .st_PointAlong(p_segmentLengthFraction => 0.50)
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINT (562013.13 1013098.431)';
      ut.expect(l_actual).to_equal(l_expected);
      
      l_actual := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,2),sdo_ordinate_array(0,0,10,10,20,0)))
                       .ST_PointAlong(p_segmentLengthFraction=>0.5)
                       .ST_AsEWKT();
      l_expected := 'POINT (10 10)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := spdba.T_Segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,2),sdo_ordinate_array(0,0,10,10,20,0)))
                       .ST_PointAlong(p_segmentLengthFraction=>0.9)
                       .ST_Round(3)
                       .ST_AsEWKT();
      l_expected := 'POINT (19.511 3.09)';
      ut.expect(l_actual).to_equal(l_expected);

      -- 2D+Z CircularArc 
      l_actual := T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,1.0, 252230.478,5527000.0,1.0)))
                       .ST_PointAlong(p_segmentLengthFraction => 0.50)
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (252409.39 5526959.187 1)';
      ut.expect(l_actual).to_equal(l_expected);

      -- 2D+M CircularArc 
      l_actual := T_Segment(SDO_GEOMETRY(3302,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00, 562044.981,1013076.691,77.1)))
                    .st_PointAlong(p_segmentLengthFraction => 0.50)
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINTM (562013.13 1013098.431 38.55)';
      ut.expect(l_actual).to_equal(l_expected);
      
   END ST_PointAlong;

   --
   -- test ST_pointalongoffset case 1: ...
   --
   PROCEDURE ST_PointAlongOffset 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
   BEGIN
      -- populate actual
      -- t_segment.ST_PointAlongOffset;
      l_actual := T_Segment(SDO_GEOMETRY(2002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171, 562044.981,1013076.691)))
                    .ST_PointAlongOffset(p_segmentLengthFraction => 0.50,
                                         p_offsetDistance => 5.0)
                    .ST_Round(3)
                    .ST_AsText();
      l_expected := 'T_Vertex(p_x=>562015.949,p_y=>1013102.561,p_z=>NULL,p_w=>NULL,p_id=>1,p_sdo_gtype=>2001,p_sdo_srid=>90000006)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(SDO_GEOMETRY(3302,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00, 562044.981,1013076.691,77.1)))
                    .ST_PointAlongOffset(p_segmentLengthFraction => 0.50, p_offsetDistance => 5.0)
                    .ST_Round(3)
                    .ST_AsText();
     l_expected := 'T_Vertex(p_x=>562015.949,p_y=>1013102.561,p_z=>38.55,p_w=>NULL,p_id=>1,p_sdo_gtype=>3301,p_sdo_srid=>90000006)';
     ut.expect(l_actual).to_equal(l_expected);

     l_actual := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                    .ST_PointAlongOffset(p_segmentLengthFraction => 0.50, p_offsetDistance => 5.0)
                    .ST_Round(3)
                    .ST_AsText();
     l_expected := 'T_Vertex(p_x=>562015.949,p_y=>1013102.561,p_z=>38.55,p_w=>50.5,p_id=>1,p_sdo_gtype=>4401,p_sdo_srid=>90000006)';
     ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(SDO_GEOMETRY(2002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171, 562044.981,1013076.691)))
                    .ST_PointAlongOffset(p_segmentLengthFraction => 0.50, p_offsetDistance => 0.0)
                    .ST_Round(3)
                    .ST_AsText();
      l_expected := 'T_Vertex(p_x=>562013.13,p_y=>1013098.431,p_z=>NULL,p_w=>NULL,p_id=>1,p_sdo_gtype=>2001,p_sdo_srid=>90000006)';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_PointAlongOffset;

   --
   -- test ST_computetangentpoint case 1: ...
   --
   PROCEDURE ST_ComputeTangentPoint 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
      NULLSELF EXCEPTION;
      PRAGMA EXCEPTION_INIT(NULLSELF,-30625);
   BEGIN
      -- populate actual
      -- t_segment.st_computetangentpoint;

      -- Expect: ORA-30625: method dispatch on NULL SELF argument is disallowed
      -- Don't create tangents against single segments (only 
      l_actual := T_Segment(
            p_Segment_id => 0,
            p_startCoord => T_Vertex(p_x=>10,p_y=>0,p_z=>2.5,p_id=>0,p_sdo_gtype=>3001,p_sdo_srid=>null),
            p_endCoord   => T_Vertex(p_x=>20,p_y=>0,p_z=>5.4,p_id=>1,p_sdo_gtype=>3001,p_sdo_srid=>null),
            p_sdo_gtype  => 3002,
            p_sdo_srid   => NULL,
            p_projected  => 1,
            p_tolerance  => 0.005,
            p_precision  => 3
       ).ST_ComputeTangentPoint(
            p_position =>'MID'
       ).ST_Round(3)
        .ST_AsEWKT();
       l_expected := 'POINTZ (15 0 3.95)';
       ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => T_Vertex(p_x=>10,p_y=>0),
          p_endCoord   => T_Vertex(p_x=>20,p_y=>0),
          p_sdo_gtype  => 2002,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_ComputeTangentPoint(
            p_position =>'FRACTION',
            p_fraction => 0.15 
       ).ST_Round(3)
        .ST_AsEWKT();
      l_expected := 'POINT (11.5 0)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => T_Vertex(p_x=>10,p_y=>0),
          p_midCoord   => T_Vertex(p_x=>15,p_y=>5),
          p_endCoord   => T_Vertex(p_x=>20,p_y=>0),
          p_sdo_gtype  => 2002,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_ComputeTangentPoint(
            p_position =>'START'
       ).ST_Round(3)
        .ST_AsEWKT();
      l_expected := 'POINT (10 2.5)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => T_Vertex(p_x=>10,p_y=>0),
          p_midCoord   => T_Vertex(p_x=>15,p_y=>5),
          p_endCoord   => T_Vertex(p_x=>20,p_y=>0),
          p_sdo_gtype  => 2002,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_ComputeTangentPoint(
            p_position =>'END'
       ).ST_Round(3)
        .ST_AsEWKT();
      l_expected := 'POINT (20 2.5)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => T_Vertex(p_x=>10,p_y=>0),
          p_midCoord   => T_Vertex(p_x=>15,p_y=>5),
          p_endCoord   => T_Vertex(p_x=>20,p_y=>0),
          p_sdo_gtype  => 2002,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_ComputeTangentPoint(
            p_position =>'FRACTION',
            p_fraction => 0.4
       ).ST_Round(3)
        .ST_AsEWKT();
      l_expected := 'POINT (15.833 5.528)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
                    SDO_GEOMETRY('CIRCULARSTRING(252230.478 5526918.373, 252400.08 5526918.373, 252230.478 5527000.0)',null)
                  ).ST_ComputeTangentPoint(
                       p_position=>'MID'
                  ).ST_Round(3)
                   .ST_AsEWKT();
      l_expected := 'POINT (252420.487 5526960.774)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(
                    p_Segment_id => 0,
                    p_startCoord => T_Vertex(p_x=>10,p_y=>0),
                    p_midCoord   => T_Vertex(p_x=>15,p_y=>5),
                    p_endCoord   => T_Vertex(p_x=>20,p_y=>0),
                    p_sdo_gtype  => 2002,
                    p_sdo_srid   => NULL,
                    p_projected  => 1,
                    p_tolerance  => 0.005,
                    p_precision  => 3
                    )
                    .ST_ComputeTangentPoint(
                        p_position  =>'FRACTION',
                        p_fraction  => 0.5
                    )
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'POINT (17.5 5)';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_computetangentpoint;

   --
   -- test ST_computetangentline case 1: ...
   --
   PROCEDURE ST_ComputeTangentLine 
   IS
      l_actual   VARCHAR2(1000);
      l_expected VARCHAR2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_computetangentline;
      l_actual := T_Geometry(
                   T_Segment(SDO_GEOMETRY('CIRCULARSTRING(252230.478 5526918.373, 252400.08 5526918.373, 252230.478 5527000.0)',28355))
                    .ST_ComputeTangentLine(
                        p_position  =>'FRACTION',
                        p_fraction  => 0.15,
                        p_unit      => 'unit=M' 
                    )
                  .ST_Round(3)
                  .ST_SdoGeometry(),0.005,1,1)
                  .ST_AsEWKT();
      l_expected := 'SRID=28355;LINESTRING (252286.182 5526869.686,252330.933 5526855.138)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Geometry(
                   T_Segment(
                    p_Segment_id => 0,
                    p_startCoord => T_Vertex(p_x=>10,p_y=>0,p_z=>0.15,p_id=>1,p_sdo_gtype=>3001,p_sdo_srid=>NULL),
                    p_midCoord   => T_Vertex(p_x=>15,p_y=>5,p_z=>0.15,p_id=>2,p_sdo_gtype=>3001,p_sdo_srid=>NULL),
                    p_endCoord   => T_Vertex(p_x=>20,p_y=>0,p_z=>0.15,p_id=>3,p_sdo_gtype=>3001,p_sdo_srid=>NULL),
                    p_sdo_gtype  => 3002,
                    p_sdo_srid   => NULL,
                    p_projected  => 1,
                    p_tolerance  => 0.005,
                    p_precision  => 3
                  )
                  .ST_ComputeTangentLine(
                        p_position  =>'FRACTION',
                        p_fraction  => 0.25,
                        p_unit      => 'unit=M' 
                  )
                  .ST_Round(3)
                  .ST_SdoGeometry(),0.005,1,1)
                  .ST_AsEWKT();
      l_expected := 'LINESTRINGZ (11.464 3.536 .15,13.232 5.303 .15)';
      ut.expect(l_actual).to_equal(l_expected);
   END ST_ComputeTangentLine;

   --
   -- test ST_linesubstring case 1: ...
   --
   PROCEDURE ST_LineSubstring 
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      -- populate actual
      -- t_segment.st_linesubstring;
      l_actual := T_Segment(SDO_GEOMETRY(3002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(562046.642,1013077.602,0, 562032.193,1013252.074,0.035)))
                   .ST_LineSubstring(
                           p_start_fraction => 0.25,
                           p_end_fraction   => 0.75,
                           p_unit           => 'unit=M'
                   )
                   .ST_Round(3)
                   .ST_AsEWKT();
      l_expected := 'SRID=90000006;LINESTRINGZ (562043.03 1013121.22 .009,562035.805 1013208.456 .026)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Fractions equal
      l_actual := T_Segment(SDO_GEOMETRY(3002,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(562046.642,1013077.602,0, 562032.193,1013252.074,0.035)))
                   .ST_LineSubstring(
                           p_start_fraction => 0.5,
                           p_end_fraction   => 0.5,
                           p_unit           => 'unit=M'
                   )
                   .ST_Round(3)
                   .ST_AsEWKT();
      l_expected := 'SRID=90000006;LINESTRINGZ (562039.418 1013164.838 .018,562039.418 1013164.838 .018)';
      ut.expect(l_actual).to_equal(l_expected);

      -- GeoDetic 
      l_actual := T_Segment(SDO_GEOMETRY(2002,8307,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),sdo_ordinate_array(147.50,-43.132,147.41,-43.387)))
                   .ST_LineSubstring(
                           p_start_fraction => 0.5,
                           p_end_fraction   => 0.9,
                           p_unit           => 'unit=M'
                   )
                   .ST_AsEWKT();
      l_expected := 'SRID=8307;LINESTRING (147.455 -43.2595,147.419 -43.3615)';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_linesubstring;

   PROCEDURE ST_ComputeDeflectionAngle 
   IS
      l_actual   varchar2(100);
      l_expected varchar2(100);
   BEGIN
      -- populate actual
      -- t_segment.ST_ComputeDeflectionAngle;
      -- populate expected
      -- ...
      l_actual := COGO.DD2DMS(T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                                .ST_ComputeDeflectionAngle(p_segment   => null)
                              );
      l_expected := '-154°17''56.969"';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := COGO.DD2DMS(T_Segment(SDO_GEOMETRY(2002,NULL,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(0,0,10,0)))
                                .ST_ComputeDeflectionAngle(p_segment   => T_Segment(SDO_GEOMETRY(2002,NULL,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(10,0,10,10))))
                              );
      l_expected := '-90°00''00.000"';
      -- assert
      ut.expect(l_actual).to_equal(l_expected);

   END ST_ComputeDeflectionAngle;

   PROCEDURE ST_AsEWKT
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
     -- dbms_output.put('CircularString (2D) ');
     l_actual := T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15)))
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D0');
     l_expected := 'CIRCULARSTRING (10.0 15.0,15.0 20.0,20.0 15.0)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString(srid with round; different format_model) ');
     l_actual := t_segment(sdo_geometry(2002,28355,NULL,sdo_elem_info_array(1,2,2),sdo_ordinate_array(252230.4743434348,5526918.37343433, 252400.034348,5526918.33434333473,252230.4434343378,5527000.433445660)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D999');
     l_expected := 'SRID=28355;CIRCULARSTRING (252230.474 5526918.373,252400.034 5526918.334,252230.443 5527000.433)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString(srid without round) ');
     l_actual := t_segment(sdo_geometry(2002,28355,NULL,sdo_elem_info_array(1,2,2),sdo_ordinate_array(252230.4743434348,5526918.37343433, 252400.034348,5526918.33434333473,252230.4434343378,5527000.433445660)))
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D999');
     l_expected := 'SRID=28355;CIRCULARSTRING (252230.474 5526918.373,252400.034 5526918.334,252230.443 5527000.433)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString(srid/3D/Z) ');
     l_actual := t_segment(SDO_GEOMETRY(3002,28355,NULL,
                              sdo_elem_info_array(1,2,2),
                              sdo_ordinate_array(252230.478,5526918.373,1.5, 252400.08,5526918.373,1.5, 252230.478,5527000.0,1.5)))
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D099');
     l_expected := 'SRID=28355;CIRCULARSTRINGZ (252230.478 5526918.373 1.5,252400.08 5526918.373 1.5,252230.478 5527000.0 1.5)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString(srid/3D/M) ');
     l_actual := t_segment(SDO_GEOMETRY(3302,28355,NULL,
                              sdo_elem_info_array(1,2,2),
                              sdo_ordinate_array(252230.478,5526918.373,0.0, 252400.08,5526918.373,417.4, 252230.478,5527000.0,506.88)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D099');
     l_expected := 'SRID=28355;CIRCULARSTRINGM (252230.478 5526918.373 0.0,252400.08 5526918.373 417.4,252230.478 5527000.0 506.88)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString(srid/4D/Z/M) ');
     l_actual := t_segment(SDO_GEOMETRY(4402,28355,NULL,
                              sdo_elem_info_array(1,2,2),
                              sdo_ordinate_array(252230.478,5526918.373,1.5,0.0, 252400.08,5526918.373,1.5,417.4, 252230.478,5527000.0,1.5,506.88)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D0');
     l_expected := 'SRID=28355;CIRCULARSTRINGZM (252230.5 5526918.4 1.5 0.0,252400.1 5526918.4 1.5 417.4,252230.5 5527000.0 1.5 506.9)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- ****************************************
     -- dbms_output.put('LineString (2D) ');
     l_actual := T_Segment(sdo_geometry(2002,NULL,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(100,100,900,900.0)))
                   .ST_AsEWKT(p_format_model => 'TM9');
     l_expected := 'LINESTRING (100 100,900 900)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('LineString(srid/2D) ');
     l_actual := T_Segment(sdo_geometry(2002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(100,100,900,900.0)))
                   .ST_AsEWKT(p_format_model => 'FM999999999999990D0');
     l_expected := 'SRID=28355;LINESTRING (100.0 100.0,900.0 900.0)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('LineString(srid/3D/Z) ');
     l_actual := T_Segment(sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1, 10,0,2)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'TM9');
     l_expected := 'SRID=28355;LINESTRINGZ (0 0 1,10 0 2)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('LineString(srid/3D/M) ');
     l_actual := T_Segment(sdo_geometry(3302,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1.5, 10,0,2.5)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'TM9');

     l_expected := 'SRID=28355;LINESTRINGM (0 0 1.5,10 0 2.5)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('LineString (SRID/4D/Z/M) ');
     l_actual := t_segment(sdo_geometry(4402,4283,null,
                               sdo_elem_info_array(1,2,1),
                               sdo_ordinate_array(147.5,-42.5,849.9,102.0, 147.6,-42.5,1923.0,2100.0)))
                   .ST_Round(3)
                   .ST_AsEWKT(p_format_model => 'TM9');
     l_expected := 'SRID=4283;LINESTRINGZM (147.5 -42.5 849.9 102,147.6 -42.5 1923 2100)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('LineString NULL ');
     l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => CAST(NULL as T_Vertex),
          p_endCoord   => CAST(NULL as T_Vertex),
          p_sdo_gtype  => 2002,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_AsEWKT();
     l_expected := 'LINESTRING EMPTY';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

     -- dbms_output.put('CircularString 3D with measures in Z ordinate ');
     l_actual := T_Segment(
          p_Segment_id => 0,
          p_startCoord => T_Vertex(p_x=>10,p_y=>0,p_z=>1.0,p_id=>1,p_sdo_gtype=>3301,p_sdo_srid=>NULL),
          p_midCoord   => T_Vertex(p_x=>15,p_y=>5,p_z=>1.0,p_id=>2,p_sdo_gtype=>3301,p_sdo_srid=>NULL),
          p_endCoord   => T_Vertex(p_x=>20,p_y=>0,p_z=>1.0,p_id=>3,p_sdo_gtype=>3301,p_sdo_srid=>NULL),
          p_sdo_gtype  => 3302,
          p_sdo_srid   => NULL,
          p_projected  => 1,
          p_tolerance  => 0.005,
          p_precision  => 3
       ).ST_AsEWKT('TM9');
     l_expected := 'CIRCULARSTRINGM (10 0 1,15 5 1,20 0 1)';
     ut.expect(l_actual).to_equal(l_expected);
     -- dbms_output.put_line(case when l_actual = l_expected then 'PASS' else 'FAIL' end);

   END ST_AsEWKT;

   PROCEDURE ST_Equals 
   IS
      l_actual   Integer;
      l_expected Integer;
   BEGIN
     -- CircularStrings String Are equal
     l_actual := T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15)))
                   .ST_Equals(T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15))));
     l_expected := 1;
     ut.expect(l_actual).to_equal(l_expected);

     -- CircularStrings Are unequal
     l_actual := T_Segment(   sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15)))
                   .ST_Equals(T_Segment(sdo_geometry (3002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,1,15,20,1,20,15,1))));
     l_expected := 0;
     ut.expect(l_actual).to_equal(l_expected);

     -- LineStrings Are equal
     l_actual := T_Segment(   sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,20,15)))
                   .ST_Equals(T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,20,15))));
     l_expected := 1;
     ut.expect(l_actual).to_equal(l_expected);

     -- LineStrings Are equal due to srid. --> returns 1 but should be 0
     l_actual := T_Segment(   sdo_geometry (2002,4326,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,20,15)))
                   .ST_Equals(T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,20,15))));
     l_expected := 1;
     ut.expect(l_actual).to_equal(l_expected);

     -- LineStrings Are unequal
     l_actual := T_Segment(   sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,  15,20)))
                   .ST_Equals(T_Segment(sdo_geometry (3002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,1,15,20,1))));
     l_expected := 0;
     ut.expect(l_actual).to_equal(l_expected);

     -- LineString/CircularString Are unequal
     l_actual := T_Segment(   sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,1),sdo_ordinate_array (10,15,15,20)))
                   .ST_Equals(T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15))));
     l_expected := 0;
     ut.expect(l_actual).to_equal(l_expected);

   END ST_Equals;   

   PROCEDURE ST_FindCircle
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      l_actual := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                    .ST_FindCircle()
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (252315.279 5526959.187 94.111)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Collinar Circular Arc
      l_actual := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(0,0,10,0,20,0)))
                    .ST_FindCircle()
                    .id;
      l_expected := '-9';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_FindCircle;

   PROCEDURE ST_Reverse
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      l_actual := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                    .ST_Reverse()
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;CIRCULARSTRING (252230.478 5527000,252400.08 5526918.373,252230.478 5526918.373)';
      ut.expect(l_actual).to_equal(l_expected);

      -- LineString with Z and M 
      l_actual := t_segment(SDO_GEOMETRY(4402,28355,NULL,
                              sdo_elem_info_array(1,2,2),
                              sdo_ordinate_array(252230.478,5526918.373,1.5,0.0, 252400.08,5526918.373,1.5,417.4, 252230.478,5527000.0,1.5,506.88)))
                    .ST_Reverse()
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;CIRCULARSTRINGZM (252230.478 5527000 1.5 506.88,252400.08 5526918.373 1.5 417.4,252230.478 5526918.373 1.5 0)';
      ut.expect(l_actual).to_equal(l_expected);
   END ST_Reverse;

   PROCEDURE ST_isReversed
   IS
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual :=                  T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(0,0,1,1)))
                    .ST_isReversed(T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(1,1,0,0))));
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_isReversed;

   PROCEDURE ST_Merge
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      -- Merged segment has three coordinates because two segments are not collinear
      l_actual :=             T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(252230.478,5526918.373,252400.08,5526918.373)))
                    .ST_Merge(T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(252400.08,5526918.373,252230.478,5527000.0))))
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;CIRCULARSTRING (252230.478 5526918.373,252400.08 5526918.373,252230.478 5527000)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Merged segment has two coordinates because two segments are collinear
      l_actual :=             T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(0,0,1,1)))
                    .ST_Merge(T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(1,1,2,2))))
                    .ST_AsEWKT();
      l_expected := 'SRID=28355;LINESTRING (0 0,2 2)';
      ut.expect(l_actual).to_equal(l_expected);
   END ST_Merge;   

   PROCEDURE ST_isCollinear
   IS
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(0,0,1,1)))
                   .ST_isCollinear(p_segment   =>T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(1,1,2,2))));
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_isCollinear;

   PROCEDURE ST_isCircularArc
   IS
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual   := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(0,0,1,1)))
                      .ST_isCircularArc();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)))
                      .ST_isCircularArc();
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_isCircularArc;

   PROCEDURE ST_Parallel
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
     -- Planar LineString
    l_actual := T_Segment(sdo_geometry(3302,NULL,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(1,1,1.1,6,6,5.95)))
                  .ST_Parallel(p_offset=>5.0)
                  .ST_Round(3,3,2,1)
                  .ST_AsEwkt();
     l_expected := 'LINESTRINGM (4.536 -2.536 1.1,9.536 2.464 5.95)';
     ut.expect(l_actual).to_equal(l_expected);

     -- Planar CircularString
     l_actual := T_Segment(SDO_GEOMETRY(2002,28355,NULL,
                           SDO_ELEM_INFO_ARRAY(1,2,2), -- Circular Arc line string
                           SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0))
                 ).ST_Parallel(p_offset=>5.0)
                  .ST_Round(3,3,2,1)
                  .ST_AsEwkt();
     l_expected := 'SRID=28355;CIRCULARSTRING (252225.973 5526916.205,252404.585 5526916.205,252225.973 5527002.168)';
     ut.expect(l_actual).to_equal(l_expected);
   END ST_Parallel;

   PROCEDURE ST_To2D
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
     l_actual := T_Segment(sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1, 10,0,2))
                 ).ST_To2D()
                  .ST_AsEWKT();
     l_expected := 'SRID=28355;LINESTRING (0 0,10 0)';
     ut.expect(l_actual).to_equal(l_expected);   

     l_actual := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0))
                 ).ST_To2D()
                  .ST_AsEWKT();
     l_expected := 'SRID=90000006;LINESTRING (561981.279 1013120.171,562044.981 1013076.691)';
     ut.expect(l_actual).to_equal(l_expected);   
   END ST_To2D;

   PROCEDURE ST_To3D
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
     -- Convert 2D segment to 3D with constant Z value of 10.0
     l_actual := T_Segment(sdo_geometry(2002,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5, -42.5, 147.6,-42.5)))
                   .ST_To3D(p_keep_measure => 0,
                            p_default_z    => 10.0)
                   .ST_AsEWKT();
    l_expected := 'SRID=4283;LINESTRINGZ (147.5 -42.5 10,147.6 -42.5 10)';
    ut.expect(l_actual).to_equal(l_expected);   

    -- Convert measured segment (no Z) to 3D with Z
    l_actual := T_Segment(sdo_geometry(3302,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5, -42.5,0.0, 147.6, -42.5, 10923.0)))
                  .ST_To3D(p_keep_measure => 1)
                  .ST_AsEWKT();
    l_expected := 'SRID=4283;LINESTRINGZ (147.5 -42.5 0,147.6 -42.5 10923)';
    ut.expect(l_actual).to_equal(l_expected);   

    -- Convert measured segment with Z to 3D with Z (throw M away)
    l_actual := T_Segment(sdo_geometry(4402,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,2000.0, 147.6,-42.5,1923.0,4000.0)))
                  .ST_To3D(p_keep_measure => 0)
                  .ST_AsEWKT();
    l_expected := 'SRID=4283;LINESTRINGZ (147.5 -42.5 849.9,147.6 -42.5 1923)';
    ut.expect(l_actual).to_equal(l_expected);   

    -- Convert measured segment with Z to 3D with M becoming Z (throw Z away)
    l_actual := T_Segment(sdo_geometry(4402,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,2000.0, 147.6,-42.5,1923.0,4000.0)))
                  .ST_To3D(p_keep_measure => 1)
                  .ST_AsEWKT();
    l_expected := 'SRID=4283;LINESTRINGZ (147.5 -42.5 2000,147.6 -42.5 4000)';
    ut.expect(l_actual).to_equal(l_expected);   
   END ST_To3D;

   PROCEDURE ST_HasM
   Is
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_HasM();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_HasM();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_HasM();
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_HasM();
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_HasM;

   PROCEDURE ST_HasZ
   Is
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_HasZ();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_HasZ();
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_HasZ();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_HasZ();
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_HasZ;

   PROCEDURE ST_Srid
   Is
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_SRID();
      l_expected := NULL;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_SRID();
      l_expected := 4326;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_SRID();
      l_expected := 90000006;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_Srid;

   PROCEDURE ST_Self
   IS
      l_actual   integer;
      l_expected integer;
      v_segment  spdba.t_segment;
   BEGIN
      v_segment  := T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)));
      l_actual   := v_segment.ST_Self().ST_Equals(v_segment);
      l_expected := 1;
      ut.expect(l_actual).to_equal(l_expected);   
   END ST_Self;

   PROCEDURE ST_Round
   IS
      l_actual         varchar2(1000);
      l_expected       varchar2(1000);
      v_segment        spdba.t_segment;
      v_vertex         spdba.t_vertex;
      v_precisionModel spdba.T_PrecisionModel;
   BEGIN
     -- Test both ST_Round functions
     
     -- One ST_Round with parameters     
     v_segment := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279376,1013120.171456,0.7125,1.98360, 562044.9818763,1013076.69972354,77.1983,99.0945)));
     l_actual  := v_segment.ST_Round(3,3,2,1)
                           .ST_AsEWKT();
     l_expected := 'SRID=90000006;LINESTRINGZM (561981.279 1013120.171 .71 2,562044.982 1013076.7 77.2 99.1)';
     ut.expect(l_actual).to_equal(l_expected);
     
     -- Same again but with PrecisionModel
     v_precisionModel := spdba.T_PrecisionModel(
                             xy => 2,
                              z => 1,
                              w => 2,
                              tolerance => 0.005
                         );
     v_segment.ST_SetPrecisionModel(v_precisionModel);
     l_actual  := v_segment.ST_Round()
                           .ST_AsEWKT();
     l_expected := 'SRID=90000006;LINESTRINGZM (561981.28 1013120.17 .7 1.98,562044.98 1013076.7 77.2 99.09)';
     ut.expect(l_actual).to_equal(l_expected);
   END ST_Round;   

   PROCEDURE ST_LRS_Dim
   IS
      l_actual   integer;
      l_expected integer;
   BEGIN
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_LRS_Dim();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_LRS_Dim();
      l_expected := 0;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_LRS_Dim();
      l_expected := 3;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_LRS_Dim();
      l_expected := 4;
      ut.expect(l_actual).to_equal(l_expected);      
   END ST_LRS_Dim;

   PROCEDURE ST_LRS_Measure_Length
   IS
      l_actual   Number;
      l_expected Number;
   BEGIN
      l_actual := ROUND(
                    T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(0,0,1,1)))
                      .ST_LRS_Measure_Length()
                    ,7);
      l_expected := 1.4142136;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := ROUND(
                    T_Segment(MDSYS.SDO_GEOMETRY(3002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(0,0,100, 1,1,101.5)))
                      .ST_LRS_Measure_Length()
                    ,7);
      l_expected := 2.0615528;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_LRS_Measure_Length();
      l_expected := 30000-100;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual   := T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_LRS_Measure_Length();
      l_expected := 99.0;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_LRS_Measure_Length;

   PROCEDURE ST_LRS_Add_Measure
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      -- LineString tests
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(0,0,100,100)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => 0.212,
                        p_end_measure   => 141.452,
                        p_unit          => NULL)
                    .ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'LINESTRINGM (0 0 .212,100 100 141.452)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => NULL,
                        p_end_measure   => NULL,
                        p_unit          => NULL)
                    .ST_Round(6)
                    .ST_AsEWKT();
      l_expected := 'LINESTRINGM (147.5 -43.132 0,147.41 -43.387 .27)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Now with GeoDetic SRID
      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(2002,8307,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,147.41,-43.387)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => NULL,
                        p_end_measure   => NULL,
                        p_unit          => 'unit=M')
                    .ST_Round(6)
                    .ST_AsEWKT();
      l_expected := 'SRID=8307;LINESTRINGM (147.5 -43.132 0,147.41 -43.387 29257.271)';
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := T_Segment(MDSYS.SDO_GEOMETRY(3002,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => NULL,
                        p_end_measure   => NULL,
                        p_unit          => NULL)
                    .ST_Round(6)
                    .ST_AsEWKT();
      l_expected := 'SRID=4326;LINESTRINGZM (147.5 -43.132 100 0,147.41 -43.387 30000 29257.271)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Circular Arc(1)
      l_actual := T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,15,20,20,15)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => NULL,
                        p_end_measure   => NULL,
                        p_unit          => NULL)
                    .ST_Round(6)
                    .ST_AsEWKT();
      l_expected := 'CIRCULARSTRINGM (10 15 0,15 20 7.854,20 15 15.708)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Circular Arc(2)
      l_actual := T_Segment(sdo_geometry (2002,NULL,null,sdo_elem_info_array (1,2,2),sdo_ordinate_array (10,15,20,15,15,10)))
                    .ST_LRS_Add_Measure(
                        p_start_measure => NULL,
                        p_end_measure   => NULL,
                        p_unit          => NULL)
                    .ST_Round(6)
                    .ST_AsEWKT();
      l_expected := 'CIRCULARSTRINGM (10 15 0,20 15 15.708,15 10 23.562)';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_LRS_Add_Measure;

   PROCEDURE ST_LRS_Compute_Measure
   IS
      l_actual   Number;
      l_expected Number;
   BEGIN
      -- Off the end
      l_actual := ROUND(
                    T_Segment(MDSYS.SDO_GEOMETRY(2002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(0,0,1,1)))
                      .ST_LRS_Compute_Measure(
                         p_vertex => T_Vertex(p_x=>1.5,p_y=>2.0,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>NULL),
                         p_unit   => null)
                    ,7);
      l_expected := 1.4142136;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := ROUND(
                    T_Segment(MDSYS.SDO_GEOMETRY(3002,NULL,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(0,0,100, 1,1,101.5)))
                      .ST_LRS_Compute_Measure(
                         p_vertex    => T_Vertex(p_x=>0.379,p_y=>0.762,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>NULL),
                         p_unit      => null)
                    ,7);
      l_expected := 1.0991715;  -- Is Length
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := ROUND(
                    T_Segment(MDSYS.SDO_GEOMETRY(3302,4326,NULL,MDSYS.SDO_ELEM_INFO_ARRAY(1,2,1),MDSYS.SDO_ORDINATE_ARRAY(147.5,-43.132,100,147.41,-43.387,30000)))
                      .ST_LRS_Compute_Measure(
                         p_vertex    => T_Vertex(p_x=>147.5912,p_y=>-43.134,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4326),
                         p_unit      => null)
                    ,3);
      l_expected := 30000;
      ut.expect(l_actual).to_equal(l_expected);

      l_actual := ROUND(
                    T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                      .ST_LRS_Compute_Measure(
                         p_vertex    => T_Vertex(p_x=>562000.0,p_y=>1013100.0,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>90000006),
                         p_unit      => null)
                    ,3);
      l_expected := 42.97;
      ut.expect(l_actual).to_equal(l_expected);
   END ST_LRS_Compute_Measure;

   --
   -- test ST_closest cases: ...
   --
   PROCEDURE ST_closest 
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
      v_segment spdba.t_segment;
      v_vertex  spdba.t_vertex;
      v_centre  spdba.t_vertex;
   BEGIN
/*
      -- Case 1: Planar 2D LineString no unit
      l_actual := T_Segment(
                     p_line => sdo_geometry('LINESTRING(5200000 300000,5200010 300010)',28355),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                  ).ST_Closest(
                        p_geometry  => sdo_geometry('POINT(5200100 300500)',28355),
                        p_unit      => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (5200300 300300)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 1: Planar 3D LineString no unit
      l_actual := T_Segment(
                     p_line       => sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,2.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                  ).ST_Closest(
                        p_geometry  => sdo_geometry(3001,28355,sdo_point_type(5200100,300500,1.5),NULL,NULL),
                        p_unit      => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (5200298.532 300298.532 30.853)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 3: Geodetic LineString
      l_actual   := T_Segment(
                     p_line       => sdo_geometry('LINESTRING(147 -43,148 -43)',8307),
                     p_segment_id => 1,
                     p_precision  => 8,
                     p_tolerance  => 0.05
                  ).ST_Closest(
                          p_vertex => T_Vertex(p_x=>147.5,p_y=>-43.734565,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>8307),
                          p_unit   => 'unit=M'
                      ).ST_Round(8)
                       .ST_AsEWKT();
      l_expected := 'SRID=8307;POINT (147.5 -43.00108819)';
      ut.expect(l_actual).to_equal(l_expected);

      -- *********************************      
      -- Case 5: Circular Arc line string
      v_segment := T_Segment(
                     p_line       => SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373,252230.478,5527000.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                   );
      v_centre  := v_segment.ST_FindCircle();
      v_vertex  := spdba.t_vertex(p_x=>v_centre.x,p_y=>v_centre.y,p_z=>NULL,p_w=>NULL,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>28355);
      l_actual  := v_segment.ST_Closest(
                                p_vertex   =>v_vertex,
                                p_unit     =>'unit=M'
                             ).ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (252230.478 5526918.373)';
      ut.expect(l_actual).to_equal(l_expected); 

      -- 2D+Ztest where point is equidistant centre of circularArc.
      v_segment := T_Segment(
                     p_line       => SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.99, 252400.08,5526918.373,1.99, 252230.478,5527000.0,1.99)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                   );
      v_centre  := v_segment.ST_FindCircle();
      v_vertex  := spdba.t_vertex(p_x=>v_centre.x,p_y=>v_centre.y,p_z=>NULL,p_w=>NULL,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>28355);
      l_actual  := v_segment.ST_Closest(
                                p_vertex    => v_vertex,
                                p_unit      => 'unit=M'
                             ).ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (252230.478 5526959.1865 1.99)';
      ut.expect(l_actual).to_equal(l_expected); 

      v_segment :=  T_Segment(
                     p_line       => SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.0005
                   );
      l_actual := v_segment.ST_Closest(
                        p_vertex => T_Vertex(p_x=>562000.0,p_y=>1013100.0,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>90000006),
                        p_unit   => null
                   ).ST_Round(3)
                    .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINTZM (562008.285 1013101.738 32.685 42.97)';
      ut.expect(l_actual).to_equal(l_expected);

     -- dbms_output.put('LineString (SRID/4D/Z/M) ');
     v_segment := t_segment(
                     p_line       => sdo_geometry(4402,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,102.0, 147.6,-42.5,1923.0,2100.0)),
                     p_segment_id => 1,
                     p_precision  => 8,
                     p_tolerance  => 0.05
                   );
     -- DEBUG dbms_output.put_line('ST_Closest.... projected= '||v_segment.projected);
     l_actual := v_segment.ST_Closest(
                         p_geometry => T_Vertex(p_x=>147.5,p_y=>-43.75,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4283).ST_SdoGeometry(),
                         p_unit     => null
                   ).ST_Round(3)
                    .ST_AsEWKT();
     l_expected := 'SRID=4326;POINTZM (147.55 -42.5 1386.45 1101)';
     ut.expect(l_actual).to_equal(l_expected);

     -- Test GeoDetic 3D SRID
     v_segment := t_segment(
                     p_line       => sdo_geometry(4402,8307,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,102.0, 147.6,-42.5,1923.0,2100.0)),                     
                     p_segment_id => 1,
                     p_precision  => 8,
                     p_tolerance  => 0.05
                   );
     l_actual := v_segment.ST_Closest(
                        p_geometry => T_Vertex(p_x=>147.5,p_y=>-43.75,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>8307).ST_SdoGeometry(),
                        p_unit     => null
                   ).ST_Round(3)
                    .ST_AsEWKT();
     l_expected := 'SRID=8307;POINTZM (147.55 -42.5 1386.45 1101)';
     ut.expect(l_actual).to_equal(l_expected);
*/
    return;
   END ST_closest;

   --
   -- test ST_PointToLinestring case 1: ...
   --
   PROCEDURE ST_PointToLinestring 
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      -- t_segment.ST_PointToLinestring;

      -- 2D Linestring
      l_actual := t_segment(
                    sdo_geometry('LINESTRING(0 0,10 10)',null)
                  ).ST_PointToLinestring(
                         t_vertex(p_x=>5,p_y=>6)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'POINT (5.5 5.5)';
      ut.expect(l_actual).to_equal(l_expected);

      -- 2D Point projected to 3D(Z) Linestring
      l_actual := t_segment(
                    sdo_geometry(3002,NULL,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(0,0,1,10,10,15.0))
                  ).ST_PointToLinestring(
                       t_vertex(p_x=>5,p_y=>6)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'POINTZ (5.253 5.253 8.354)';
      ut.expect(l_actual).to_equal(l_expected);

      -- 2D + Z + M LineString
      -- Off starting end
      l_actual := t_segment(
                   T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                  ).ST_PointToLinestring(
                       T_Vertex(p_x=>561900.0,p_y=>1013100.0,p_z=>1.0,p_id=>0,p_sdo_gtype=>3001,p_sdo_srid=>90000006)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINTZM (561981.279 1013120.171 0 1)';
      ut.expect(l_actual).to_equal(l_expected);
      
      -- Off end
      l_actual := t_segment(
                   T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                  ).ST_PointToLinestring(
                       T_Vertex(p_x=>562037.527,p_y=>1013024.119,p_z=>75.1,p_id=>0,p_sdo_gtype=>3001,p_sdo_srid=>90000006)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINTZM (562044.981 1013076.691 77.1 100)';
      ut.expect(l_actual).to_equal(l_expected);

      -- In middle 
      l_actual := t_segment(
                   T_Segment(SDO_GEOMETRY(4402,90000006,NULL,SDO_ELEM_INFO_ARRAY(1,2,1),SDO_ORDINATE_ARRAY(561981.279,1013120.171,0.00,1.0, 562044.981,1013076.691,77.1,100.0)))
                  ).ST_PointToLinestring(
                       T_Vertex(p_x=>562024.067,p_y=>1013118.902,p_z=>50.0,p_id=>0,p_sdo_gtype=>3001,p_sdo_srid=>90000006)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'SRID=90000006;POINTZM (562016.823 1013095.91 43.019 56.239)';  -- SGG
      ut.expect(l_actual).to_equal(l_expected);

   END ST_PointToLinestring;

   PROCEDURE ST_PointToCircularArc
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
      v_segment  spdba.t_segment;
      v_vertex   spdba.t_vertex;
   BEGIN
     -- Half circle Circular Arc
     v_segment  := t_segment(SDO_GEOMETRY(2002,NULL,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(0,0,5,5,10,0)));
     -- ON 
     v_vertex   := t_vertex(SDO_GEOMETRY(2001,NULL,SDO_POINT_TYPE(13.493,2.316,null),null,null));
     l_actual   := v_segment.ST_PointToCircularArc(v_vertex,null)
                            .ST_Round(3)
                            .ST_AsEWKT();
     l_expected := 'POINTM (9.824 1.315 -14.377)';
     ut.expect(l_actual).to_equal(l_expected);
     -- OFF
     v_vertex   := t_vertex(SDO_GEOMETRY(2001,NULL,SDO_POINT_TYPE(7.358,-1.69,null),null,null));
     l_actual   := case when v_segment.ST_PointToCircularArc(v_vertex,null) is null then NULL else 'ERROR' End;
     l_expected := NULL;
     ut.expect(l_actual).to_equal(l_expected);

     -- Big 3D CircularArc
     v_segment  := t_segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,2.0, 252400.08,5526918.373,2.0, 252230.478,5527000.0,2.0)));     
     -- In Gap
     v_vertex   := t_vertex(SDO_GEOMETRY(2001,28355,SDO_POINT_TYPE(252168.108,5526967.214,NULL),NULL,NULL));
     l_actual   := case when v_segment.ST_PointToCircularArc(v_vertex,null) is null then NULL else 'ERROR' End;
     l_expected := NULL;
     ut.expect(l_actual).to_equal(l_expected);

     -- On 3002 Arc -> 4401 (measure in w position based on length)
     v_vertex   := t_vertex(SDO_GEOMETRY(2001,28355,SDO_POINT_TYPE(252328.658,5527017.673,NULL),NULL,NULL));
     l_actual   := v_segment.ST_PointToCircularArc(v_vertex,null)
                            .ST_Round(3)
                            .ST_AsEWKT();
     l_expected := 'SRID=28355;POINTZM (252336.265 5527050.928 2 895.13)';
     ut.expect(l_actual).to_equal(l_expected);
     
      -- 2D CircularString (Returned Measure is based on Length)
      l_actual := t_segment(
                    sdo_geometry('CIRCULARSTRING(0 0,10 5,20 0)',null)
                  ).ST_PointToCircularArc(
                         t_vertex(p_x=>5,p_y=>6)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'POINTM (5.659 4.222 7.157)';
      ut.expect(l_actual).to_equal(l_expected);

      -- 2D+Z CircularString
      l_actual := t_segment(
                   T_Segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,1.0, 252400.08,5526918.373,1.0, 252230.478,5527000.0,1.0)))
                  ).ST_PointToCircularArc(
                       T_Vertex(p_x=>2522000.0,p_y=>5526900.0,p_z=>1.0,p_id=>0,p_sdo_gtype=>3001,p_sdo_srid=>NULL)
                  )
                  .ST_Round(3)
                  .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZM (252409.39 5526959.184 1 -1074.119)';
      ut.expect(l_actual).to_equal(l_expected);

   END ST_PointToCircularArc;

   PROCEDURE ST_isPointOnSegment
   Is
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      v_segment  t_segment;
      v_vertex   t_vertex;
   Begin
     -- On Arc (3002 same as 2002 in length 'cos all z ordinates are the same).
     v_segment  := t_segment(SDO_GEOMETRY(3002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373,2.0, 252400.08,5526918.373,2.0, 252230.478,5527000.0,2.0)));     
     v_segment  := t_segment(SDO_GEOMETRY(2002,28355,NULL,SDO_ELEM_INFO_ARRAY(1,2,2),SDO_ORDINATE_ARRAY(252230.478,5526918.373, 252400.08,5526918.373, 252230.478,5527000.0)));     
     v_vertex   := t_vertex (SDO_GEOMETRY('POINT (252336.265 5527050.928)',28355));
     l_actual   := v_segment.ST_isPointOnSegment(v_vertex,null);
     l_expected := 1;
     ut.expect(l_actual).to_equal(l_expected);
   End ST_isPointOnSegment;

   PROCEDURE ST_ProjectPoint
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
      v_segment spdba.t_segment;
      v_vertex  spdba.t_vertex;
   BEGIN
     -- LineString
     --
     -- Case 1: Planar 2D LineString no unit
     v_segment := T_Segment(
                     p_line => sdo_geometry('LINESTRING(5200000 300000,5200010 300010)',28355),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                  );
     l_actual := v_segment.ST_ProjectPoint(
                        p_vertex => t_vertex(sdo_geometry('POINT(5200100 300500)',28355)),
                        p_unit   => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINT (5200010 300010)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 1: 2D Vertex against 3D LineString (planar, no unit)
      v_segment := T_Segment(
                     p_line       => sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,2.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                   );
      l_actual  := v_segment.ST_ProjectPoint(
                        p_vertex => t_vertex(sdo_geometry(2001,28355,sdo_point_type(5200100,300500,NULL),NULL,NULL)),
                        p_unit   => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (5200010 300010 2)';  -- SGG
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 2: 3D Point against 3D LineString (planar no unit)
      v_segment := T_Segment(
                     p_line       => sdo_geometry(3002,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,2.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                   );
      l_actual  := v_segment.ST_ProjectPoint(
                        p_vertex => t_vertex(sdo_geometry(3001,28355,sdo_point_type(5200100,300500,1.5),NULL,NULL)),
                        p_unit   => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTZ (5200010 300010 2)';
      ut.expect(l_actual).to_equal(l_expected);

      -- Case 3: 2D Point against 3D(M) LineString (planar no unit)
      v_segment := T_Segment(
                     p_line       => sdo_geometry(3302,28355,NULL,sdo_elem_info_array(1,2,1),sdo_ordinate_array(5200000,300000,1.0, 5200010,300010,14.0)),
                     p_segment_id => 1,
                     p_precision  => 3,
                     p_tolerance  => 0.005
                   );
      l_actual  := v_segment.ST_ProjectPoint(
                        p_vertex => t_vertex(sdo_geometry(2001,28355,sdo_point_type(5200100,300500,null),NULL,NULL)),
                        p_unit   => NULL
                    ).ST_Round(3)
                     .ST_AsEWKT();
      l_expected := 'SRID=28355;POINTM (5200010 300010 14)';
      ut.expect(l_actual).to_equal(l_expected);

     -- ******************************************************************************
     -- CircularArc
     -- dbms_output.put('LineString (SRID/4D/Z/M) ');
-- SGG PROBLEM
     v_segment := t_segment(
                     p_line       => sdo_geometry(4402,4283,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,102.0, 147.6,-42.5,1923.0,2100.0)),
                     p_segment_id => 1,
                     p_precision  => 8,
                     p_tolerance  => 0.05
                   );
     -- DEBUG dbms_output.put_line('ST_ProjectPoint....');
     l_actual := v_segment.ST_ProjectPoint(
                         p_vertex => T_Vertex(p_x=>147.6,p_y=>-42.75,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>4283),
                         p_unit   => null
                   ).ST_Round()
                    .ST_AsEWKT();
     l_expected := 'SRID=4283;POINTZM (147.59980009 -42.50000009 849.9 2096.006)';
     ut.expect(l_actual).to_equal(l_expected);

     -- Test GeoDetic 3D SRID
     v_segment := t_segment(
                     p_line       => sdo_geometry(4402,8307,null,sdo_elem_info_array(1,2,1),sdo_ordinate_array(147.5,-42.5,849.9,102.0, 147.6,-42.5,1923.0,2100.0)),                     
                     p_segment_id => 1,
                     p_precision  => 8,
                     p_tolerance  => 0.05
                   );
     l_actual := v_segment.ST_ProjectPoint(
                        p_vertex => T_Vertex(p_x=>147.495,p_y=>-42.75,p_id=>0,p_sdo_gtype=>2001,p_sdo_srid=>8307),
                        p_unit   => null
                   ).ST_Round()
                    .ST_AsEWKT();
     l_expected := 'SRID=8307;POINTZM (147.5 -42.5 849.9 102)';
     ut.expect(l_actual).to_equal(l_expected);

   END ST_ProjectPoint;

   PROCEDURE ST_IntersectCircularArc
   IS
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
      l_actual := spdba.t_segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,2),sdo_ordinate_array(0,0,10,10,20,0)))
            .ST_IntersectCircularArc(
                p_segment => spdba.t_segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,1),SDO_ORDINATE_ARRAY(10,0,10,12))),
                p_unit    => null)
            .ST_Round(3)
            .ST_AsText();
       l_expected := 'T_Segment(p_element_id=>NULL,p_subelement_id=>NULL,p_segment_id=>1,p_startCoord=>T_Vertex(p_x=>10,p_y=>-10,p_z=>NULL,p_w=>NULL,p_id=>1,p_sdo_gtype=>2001,p_sdo_srid=>NULL),p_midCoord=>T_Vertex(p_x=>0,p_y=>0,p_z=>NULL,p_w=>NULL,p_id=>1,p_sdo_gtype=>2001,p_sdo_srid=>NULL),p_endCoord=>T_Vertex(p_x=>NULL,p_y=>NULL,p_z=>NULL,p_w=>NULL,p_id=>3,p_sdo_gtype=>2001,p_sdo_srid=>NULL),p_sdo_gtype=>2002,p_sdo_srid=>NULL)';
     ut.expect(l_actual).to_equal(l_expected);
   END ST_IntersectCircularArc;
   
   PROCEDURE ST_Intersect2CircularArcs
   IS 
      l_actual   varchar2(1000);
      l_expected varchar2(1000);
   BEGIN
     l_actual := spdba.t_segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,2),sdo_ordinate_array(0,0,10,10,20,0)))
                      .ST_Intersect2CircularArcs(
                          p_segment => spdba.t_segment(mdsys.sdo_geometry(2002,null,null,sdo_elem_info_array(1,2,2),SDO_ORDINATE_ARRAY(9.959,-0.004, 14.719,5.245, 8.133,13.623))),
                          p_unit    => null)
                      .ST_Round(3)
                      .ST_AsText();
     l_expected := 'T_Segment(p_element_id=>NULL,p_subelement_id=>NULL,p_segment_id=>1,p_startCoord=>T_Vertex(p_x=>14.477,p_y=>8.942,p_z=>NULL,p_w=>NULL,p_id=>1,p_sdo_gtype=>2001,p_sdo_srid=>NULL),p_midCoord=>NULL,p_endCoord=>T_Vertex(p_x=>1.189,p_y=>4.729,p_z=>NULL,p_w=>NULL,p_id=>3,p_sdo_gtype=>2001,p_sdo_srid=>NULL),p_sdo_gtype=>2002,p_sdo_srid=>NULL)';
     ut.expect(l_actual).to_equal(l_expected);
   END ST_Intersect2CircularArcs;
   
END test_t_segment;
/
show errors

SET SERVEROUTPUT ON SIZE UNLIMITED
EXECUTE ut.run('SPDBA.TEST_T_SEGMENT');

-- SGG: compare ST_Closest and ST_PointToSegment for planar
-- SGG Check ST_CLosest for > 2D circular arcs
-- Check ST_Closest for 
